apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headline-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Shirleyu98/Springboot-Headline-App"
    path: headline-app
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
