image:
  frontend:
    repository: shirleycutie/clientforheadlineapp
    tag: latest
    pullPolicy: IfNotPresent
  backend:
    repository: shirleycutie/serverforheadlineapp
    tag: latest
    pullPolicy: IfNotPresent
service:
  frontend:
    type: ClusterIP
    port: 80
  backend:
    type: ClusterIP
    port: 8080
